/*
 Navicat Premium Data Transfer

 Source Server         : EksiCode-TEST
 Source Server Type    : PostgreSQL
 Source Server Version : 100012
 Source Host           : 116.203.85.45:33333
 Source Catalog        : eksicodedev
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 100012
 File Encoding         : 65001

 Date: 16/08/2020 21:09:02
*/


-- ----------------------------
-- Sequence structure for Role_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Role_id_seq";
CREATE SEQUENCE "public"."Role_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for Users_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Users_id_seq";
CREATE SEQUENCE "public"."Users_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for Role
-- ----------------------------
DROP TABLE IF EXISTS "public"."Role";
CREATE TABLE "public"."Role" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "name" text COLLATE "pg_catalog"."default",
  "created_at" timestamp(6) NOT NULL,
  "updated_at" timestamp(6) NOT NULL,
  "status" bool NOT NULL
)
;

-- ----------------------------
-- Records of Role
-- ----------------------------

-- ----------------------------
-- Table structure for Users
-- ----------------------------
DROP TABLE IF EXISTS "public"."Users";
CREATE TABLE "public"."Users" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "first_name" text COLLATE "pg_catalog"."default" NOT NULL,
  "last_name" text COLLATE "pg_catalog"."default" NOT NULL,
  "username" text COLLATE "pg_catalog"."default" NOT NULL,
  "password" text COLLATE "pg_catalog"."default" NOT NULL,
  "email" text COLLATE "pg_catalog"."default" NOT NULL,
  "avatar" text COLLATE "pg_catalog"."default",
  "phone" text COLLATE "pg_catalog"."default",
  "recovery_code" text COLLATE "pg_catalog"."default",
  "reputation" text COLLATE "pg_catalog"."default",
  "impact" text COLLATE "pg_catalog"."default",
  "badges" text COLLATE "pg_catalog"."default",
  "socials" text COLLATE "pg_catalog"."default",
  "role_id" int4 NOT NULL,
  "created_at" timestamp(6) NOT NULL,
  "updated_at" timestamp(6) NOT NULL,
  "status" bool NOT NULL
)
;

-- ----------------------------
-- Records of Users
-- ----------------------------

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Role_id_seq"
OWNED BY "public"."Role"."id";
SELECT setval('"public"."Role_id_seq"', 2, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Users_id_seq"
OWNED BY "public"."Users"."id";
SELECT setval('"public"."Users_id_seq"', 2, false);

-- ----------------------------
-- Primary Key structure for table Role
-- ----------------------------
ALTER TABLE "public"."Role" ADD CONSTRAINT "PK_Role" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table Users
-- ----------------------------
CREATE INDEX "IX_Users_role_id" ON "public"."Users" USING btree (
  "role_id" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table Users
-- ----------------------------
ALTER TABLE "public"."Users" ADD CONSTRAINT "PK_Users" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table Users
-- ----------------------------
ALTER TABLE "public"."Users" ADD CONSTRAINT "FK_Users_Role_role_id" FOREIGN KEY ("role_id") REFERENCES "public"."Role" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
